    // depends: baja; program; history

    import javax.baja.naming.BOrd;
    import javax.baja.sys.*;
    import com.tridium.program.*;
    import javax.baja.history.*;
    import javax.baja.bql.*;
    import javax.baja.collection.*;

    public class RobotImpl extends Robot {
    /****************************
     *********************
     *************
        add set group names to specified devices
        &
        add Device String slot for history grouping

        ONLY WORKS ON  DEVICE TYPE - bacnet:BacnetDevice

        Paste text into Robot Editor.
     *************
     *********************
     ***************************
     */


        public void run()
                throws Exception {
            process(Sys.getStation());
            log.println("complete");
        }

        public void process(BComponent c)
                throws Exception {

            /*
               edit ord variable to folder that you wish to add Device String to HistoryConfig
               edit groups for total number of folders {slot name, folder name} not counting device folder.
            */
            String ord = "enter Ord here";
            String[][] groups = {{"FirstTier", "name"}, {"SecondTier", "name"}, {"ThirdTier", "name"}};
            /*
             *
             *
             *
             *
             *
             */
            String bql = "bql:select * from history:HistoryConfig";
            BOrd query = BOrd.make(ord + "|" + bql);
            BITable result = (BITable) query.resolve().get();
            Cursor crs = result.cursor();
            //loop through table generated by bql query
            while (crs.next()) {
                BComponent config = (BComponent) crs.get();
                BComponent parent = (BComponent) crs.get();
                //if the parent is not null get the Type and see if it is a BacnetDevice. if its not keep going up
                while (parent != null && !parent.getType().toString().equals("bacnet:BacnetDevice") && parent.getParent() != null) {
                    parent = parent.getParent().asComponent();
                }
                //parent is now a bacnetDevice add folders from groups and lastly a Device folder, if the folders exist already then set the value of the BString
                //or
                // if the historyConfig did not have a bacnetDevice above it, skip.
                if (parent != null && parent.getParent() != null) {
                        for (String[] g : groups) {
                            try {
                                config.add(g[0], BString.make(g[1]));
                            } catch (LocalizableRuntimeException e) {
                                config.set(g[0], BString.make(g[1]));
                            }
                        }
                        try {
                            config.add("Device", BString.make(parent.getName()));
                        } catch (LocalizableRuntimeException e) {
                            config.set("Device", BString.make(parent.getName()));
                        }

                }
            }

        }
    }
